---
- name: Securing Server
  hosts: all
  become: yes
  tasks:
    - name: Update sshd_config.conf
      ansible.builtin.template:
        src: sshd_config.conf
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'

    - name: Restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
        enabled: yes

    - name: Update IPSet & IPTables rules
      include_role:
        name: iptables