---
- name: check {{ username }} user exists
  ansible.builtin.getent:
    database: passwd
    key: "{{ username }}"
  register: admin_user
  ignore_errors: yes

- name: Create {{ username }} user
  user:
    state: present
    name: "{{ username }}"
    groups: sudo
    append: yes
    shell: /bin/bash
    createhome: yes
  when: admin_user.failed == true

- name: Grant NOPASSWD to sudo group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo   ALL=(ALL:ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  when: admin_user.failed == true

- name: set password for {{ username }} user
  user:
    name: "{{ username }}"
    password: "{{ vault_ssh_admin_password | password_hash('sha512') }}"

- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  notify: restart sshd

- name: Add SSH keys for {{ username }} user from templates
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - ./private/keys/*.pub
  when: admin_user.failed == true